server:
  port: 10000
  servlet:
    session:
      cookie:
        name: GULI-SESSION
        # 为了实现 session 跨域所有微服务都使用父域名
        domain: gulimall.com

logging:
  level:
    cn.edu.zjut: debug

spring:
  application:
    name: gulimall-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gulimall_pms
    username: root
    password: root
  # 指定时间格式化规则
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
  cache:
    type: redis
    redis:
      # 禁用前缀（包括 cacheName::）
      # use-key-prefix: false
      # 如果没有指定 prefix，前缀就为 cacheName::
      # key-prefix: CACHE_
      # 缓存空值，防止缓存穿透
      cache-null-values: true
      # 单位：ms
      time-to-live: 3600000
  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      # 主键自增
      id-type: auto
      # 逻辑删除[0-不显示，1显示]
      logic-not-delete-value: 1
      logic-delete-value: 0

# 线程池
thread:
  pool:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
    queue-length: 100000
