spring:
  application:
    name: gulimall-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gulimall_pms
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # 主键自增
  global-config:
    db-config:
      id-type: auto

server:
  port: 10000
logging:
  level:
    cn.edu.zjut: debug