server:
  port: 7000
  servlet:
    session:
      cookie:
        name: GULI-SESSION
        # 为了实现 session 跨域所有微服务都使用父域名
        domain: gulimall.com

logging:
  level:
    cn.edu.zjut: debug

spring:
  application:
    name: gulimall-coupon
  cloud:
    # 到服务中心注册
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gulimall_sms
    username: root
    password: root
  # 指定时间格式化规则（前端传了毫秒值）
  #  jackson:
  #    date-format: yyyy-MM-dd HH:mm:ss.SSS
  #    time-zone: GMT+8
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # 主键自增
  global-config:
    db-config:
      id-type: auto
      # 逻辑删除[0-不显示，1显示]
      logic-not-delete-value: 1
      logic-delete-value: 0

