server:
  port: 20000
  servlet:
    session:
      cookie:
        name: GULI-SESSION
        # 为了实现 session 跨域所有微服务都使用父域名
        domain: gulimall.com

logging:
  level:
    cn.edu.zjut: debug

spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis
