server:
  port: 9000
  servlet:
    session:
      cookie:
        name: GULI-SESSION
        # 为了实现 session 跨域所有微服务都使用父域名
        domain: gulimall.com

logging:
  level:
    cn.edu.zjut: debug

spring:
  application:
    name: gulimall-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gulimall_oms
    username: root
    password: root
  # 指定时间格式化规则
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  # 主键自增
  global-config:
    db-config:
      id-type: auto
      # 逻辑删除[0-不显示，1显示]
      logic-not-delete-value: 1
      logic-delete-value: 0

# 线程池
thread:
  pool:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
    queue-length: 100000
