spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  jackson:
    date-format: yyyy-MM-dd HH:mmm:ss
    time-zone: GMT+8

  thymeleaf:
    cache: false

#  redis:
#    port: 6379
#    host: 127.0.0.1
#  session:
#    store-type: redis

server:
  port: 12000
logging:
  level:
    cn.edu.zjut: debug