spring:
  application:
    name: gulimall-gateway
  cloud:
    # \u5230\u670D\u52A1\u4E2D\u5FC3\u6CE8\u518C
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 88
logging:
  level:
    cn.edu.zjut: debug
