spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        # - id: jd_route
        #   uri: https://www.jd.com
        #   predicates:
        #     - Query=url,jd
        # - id: qq_route
        #   uri: https://www.qq.com
        #   predicates:
        #     - Query=url,qq

        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*), /$\{segment}

        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          # 过滤前验证码请求路径 http://localhost:88/api/captcha.jpg?uuid=69c79f02-d15b-478a-8465-a07fd09001e6
          # 由于 renren-fast 已在注册中心注册，网关可以通过注册中心知道 renren-fast 的 ip 和端口
          # 过滤后验证码请求路径 http://localhost:8080/renren-fast/captcha.jpg?uuid=69c79f02-d15b-478a-8465-a07fd09001e6
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}

        - id: host_route
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com

        - id: search_route
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com

  # 指定时间格式化规则
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false

server:
  port: 88

logging:
  level:
    cn.edu.zjut: debug
