spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: jd_route
          uri: https://www.jd.com
          predicates:
            - Query=url,jd

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq


server:
  port: 88

logging:
  level:
    cn.edu.zjut: debug
