server:
  port: 30000
  servlet:
    session:
      cookie:
        name: GULI-SESSION
        # 为了实现 session 跨域所有微服务都使用父域名
        domain: gulimall.com

logging:
  level:
    cn.edu.zjut: debug

spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tL9N78zRsi5VD57eumf
      secret-key: 1vTfVeUxut6t33WHwPxEWFzuRYvCBK
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: zett0n-gulimall
  # 指定时间格式化规则
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 127.0.0.1
  session:
    store-type: redis

