spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tL9N78zRsi5VD57eumf
      secret-key: 1vTfVeUxut6t33WHwPxEWFzuRYvCBK
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: zett0n-gulimall
  # 指定时间格式化规则
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false

server:
  port: 30000

logging:
  level:
    cn.edu.zjut: debug
