server:
  port: 30000
  servlet:
    session:
      cookie:
        name: GULI-SESSION
        # 为了实现 session 跨域所有微服务都使用父域名
        domain: gulimall.com

logging:
  level:
    cn.edu.zjut: debug
    # 用于查看 sleuth 日志
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug

spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        # sentinel server
        dashboard: 127.0.0.1:8858
    alicloud:
      access-key: LTAI5tL9N78zRsi5VD57eumf
      secret-key: 1vTfVeUxut6t33WHwPxEWFzuRYvCBK
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: zett0n-gulimall
  zipkin:
    base-url: 127.0.0.1:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  # 指定时间格式化规则
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 127.0.0.1
  session:
    store-type: redis

# springboot 监控
management:
  endpoints:
    web:
      exposure:
        include: '*'